export const fakeData = {
  location: 'FakeParis',
  current: {
    temp: 12,
    description: 'Ensoleillé',
    wind: 12,
    humidity: 12,
    max: 12,
    min: 12,
  },
  day: [
    {
      global: {
        temp: 12,
        description: 'Ensoleillé',
        max: 12,
        min: 12,
      },
      hourly: [
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
      ],
    },
    {
      global: {
        temp: 12,
        description: 'Ensoleillé',
        max: 12,
        min: 12,
      },
      hourly: [
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
        {
          temp: 12,
          description: 'Ensoleillé',
          max: 12,
          min: 12,
        },
      ],
    },
  ],
}
